# Generated by Django 4.1.3 on 2023-03-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plastics_eol", "0002_remove_condition_id_remove_exportedplastic_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mswcomposition",
            name="total_mass",
            field=models.FloatField(default=0.0),
        ),
    ]
