# Generated by Django 4.1.3 on 2023-03-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plastics_eol", "0003_mswcomposition_total_mass"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plasticincineration",
            old_name="pal",
            new_name="pla",
        ),
        migrations.RenameField(
            model_name="plasticlandfill",
            old_name="pal",
            new_name="pla",
        ),
        migrations.RenameField(
            model_name="plasticrecycling",
            old_name="pal",
            new_name="pla",
        ),
        migrations.RenameField(
            model_name="plasticreportedrecycled",
            old_name="pal",
            new_name="pla",
        ),
    ]
