# settings.py (plastics_eol)
# !/usr/bin/env python3
# coding=utf-8

"""
Django settings for plastics_eol project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from os.path import join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Descriptions and APP Names
APP_NAME = 'GS End of Life Plastic Additives'
APP_NAME_SHORT = 'plastics_eol'

APP_DESCRIPTION_SHORT = 'TODO short app description.'
APP_DESCRIPTION_LONG = 'TODO long app description.'

APP_VERSION = '0.0.1-beta'

# User Manual and Folder Location of Downloadables
MANUAL_NAME = 'Suppl Info -GS of EoL Plastic Additives_FINAL_postProof.docx'
DOWNLOADS_DIR = join(BASE_DIR, '..', 'docs')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Note: Git might complain about this secret being exposed. However, this
# secret is not used in any production settings and thus is not a security risk.
# For production environments, this SECRET_KEY will be overridden with a
# different protected value via local_settings.py or a .env file.
SECRET_KEY = 'django-insecure-h&jjm2=hrxojts#7&17g*lsvo5tc2ko(7%-5)!2jsba#w%zyd='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'constants',
    'disclaimers',
    'support',
    'teams',
    'plastics_eol',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plastics_eol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plastics_eol.context_processors.selected_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'plastics_eol.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'plastics_eol',
        'USER': 'postgres',
        'PASSWORD': 'YOUR USER PASSWORD SHOULD BE DEFINED IN LOCAL_SETTINGS.PY',
        'HOST': 'localhost',
        'PORT': '5433'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    from .local_settings import *
except ImportError:
    pass
